version: "3.8"
services:
  keycloak:
    image: jboss/keycloak
    ports:
    - "8080:8080"
    networks:
      - keycloak
    environment:
#      - KEYCLOAK_USER=root
#      - KEYCLOAK_PASSWORD=root
      - DB_ADDR=db_keycloack
      - DB_PORT=5432
      - DB_NAME=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - MAX_POOL_SIZE=1000
      - DB_VENDOR=postgres
  db_keycloack:
    image: postgres:12
    volumes:
      - dbkeycloak:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - keycloak

volumes:
  dbkeycloak:
    name: dbdata

networks:
  keycloak:
    name: keycloak_network
    driver: bridge